# see https://www.compart.com/en/unicode/category
CATEGORIES = {
    'Cc': 'Control',
    'Cf': 'Format',
    'Co': 'Private Use',
    'Cs': 'Surrrogate',
    'Ll': 'Lowercase Letter',
    'Lm': 'Modifier Letter',
    'Lo': 'Other Letter',
    'Lt': 'Titlecase Letter',
    'Lu': 'Uppercase Letter',
    'Mc': 'Spacing Mark',
    'Me': 'Enclosing Mark',
    'Mn': 'Nonspacing Mark',
    'Nd': 'Decimal Number',
    'Nl': 'Letter Number',
    'No': 'Other Number',
    'Pc': 'Connector Punctuation',
    'Pd': 'Dash Punctuation',
    'Pe': 'Close Punctuation',
    'Pf': 'Final Punctuation',
    'Pi': 'Initial Punctuation',
    'Po': 'Other Punctuation',
    'Ps': 'Open Punctuation',
    'Sc': 'Currency Symbol',
    'Sk': 'Modifier Symbol',
    'Sm': 'Math Symbol',
    'So': 'Other Symbol',
    'Zl': 'Line Separator',
    'Zp': 'Paragraph Separator',
    'Zs': 'Space Separator',
}